### ISSUE TITLE
Worktime grouped by weeks

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [soywod/kronos.vim#24]
The readme says:
> The worktime allows you to check how much time you spent on one or many tags, grouped by day. Press gw (for go to worktime), and type the tags you want to calculate the total worktime:

Is there a way to check how much time spent on a task and also to show the time spent on a task in weeks instead of hours? 

Over long durations, time spent in weeks would be more meaningful than time spent in hours of each day

**Comment by soywod** [comment]
You can get the total worktime for a task via the [info binding](https://github.com/soywod/kronos.vim#read) (`K` by default). You have a key `WORKTIME` at the end.

For the other question, it's not possible for now to group by weeks, I will check how to set up this.

**Comment by ChukwuemezieChristopherAneke** [comment]
@soywod thanks for answering my first question. As for the second question, viewing time totals by day, week, month or even a year (e.g. the task of learning a spoken language can take years) would be useful enhancements but weekly time totals is a good start. Do you plan to base viewing weekly time totals by a working week (i.e. 5 days) or a full week (i.e. 7 days)?

Basing weekly time totals on a working week would be useful for work related tasks but may not be best for personal tasks which can be done on weekends. Where as basing weekly time totals on a full week could still work for work related tasks may be with a way to explicitly exclude days such as weekends for particular work related tasks

**Comment by soywod** [comment]
To be honest, it sounds to complicated for me. I created Kronos because I wanted something really simple. If someone wants to do such advanced requests, then he should consider moving to Taskwarrior or equivalent.

I plan to set Taskwarrior as a backend for Kronos (as an option). This way, Kronos stays simple as it is now, and if you need some advanced queries, you can do them via the command line (directly to the backend without passing by the client). This sounds like a good compromise. What do you think?

**Comment by ChukwuemezieChristopherAneke** [comment]
Can you clarify what you mean by setting Taskwarrior as a backend for Kronos? Does this mean to pass tasks stored in Kronos's data files to another command line program like Taskwarrior to perform queries without having to go through Kronos and vim?

I agree there is no need for Kronos to become bloated since Taskwarrior already exists for advanced queries. May be I overcomplicated it a little, I think this issue should be left open as a possible future enhancement since adding only weekly time totals should still keep Kronos simple

**Comment by soywod** [comment]
Instead of using a simple file to store tasks, I was thinking (via on option to activate) to store tasks directly into Taskwarrior. From the Kronos user, it changes nothing. But this allows him to do advanced queries via Taskwarrior CLI, since they will share the same database.

I will have a look on how to proceed such an improvement, I let the issue opened.

**Comment by ChukwuemezieChristopherAneke** [comment]
That sounds like a good way of integrating Kronos with Taskwarrior, the user can use both editor (Kronos in vim) and command line which are the main tools in many peoples workflow

**Comment by soywod** [comment]
I checked how to do, and it requires a new function with a new mapping. And tomorrow, someone else will have another request to group by hour, so a new function / mapping will be needed etc. I really prefer to keep it simple. Grouping by days is (I think) the most common case and the most useful. I just pushed sth about [Taskwarrior as a backend](https://github.com/soywod/kronos.vim/pull/25), I advise you to set up it to get the stats you need. 

If the project gets bigger, I will reconsider the question, but for now I prefer to not touch the worktime. I hope you understand.
